### ISSUE TITLE
Add YAML, HTML and file assertions

### ISSUE THREAD

**Issue by SimonBaeumer** [commander-cli/commander#105]
- [ ] HTML assertion
   - [ ] Array support
 - [ ] YAML support
   - [ ] Array support
 - [ ] File assertion

**Comment by dylanhitt** [comment]
By 'File assertion' do you mean validating that stdout matched against a file? If so I've found myself needing it. I'd look into this if so. 

Apologies for the spam, I've just been grooming through issues to try to get an understanding of your desired features.

Thanks

**Comment by SimonBaeumer** [comment]
Exactly, it should just assert against a file. 

No problem, feel free to comment as much as you want. I just used the issues as my reminders, so don't expect too much details, it is better to ask for clarifications :D
