### ISSUE TITLE
Fetch test suites from remotes and stdin

### ISSUE THREAD

**Issue by SimonBaeumer** [commander-cli/commander#109]
It would be nice to fetch test suites from remote locations like gist.github, http, https etc
Further addin stdin support

**Comment by dylanhitt** [comment]
Do you have any plans on working this? I was thinking about adding fetching from remote on my list of todos. I figure something like `commander test -remote https://github.com/SimonBaeumer/commander/blob/master/examples/environment.yaml`.


I don't think I will tackle stdin as that implementation could get pretty subjective.

**Comment by SimonBaeumer** [comment]
Yes would be very nice! I think `--url` is a little bit better than `remote` because there could be other implementation too, like sftp or ftp.
`commander test --url=https//...`

What do you mean by `could get pretty subjective`? I would think of something like this:

`echo "tests: ..." > commander test -`

**Comment by dylanhitt** [comment]
Oh I misinterpreted what you meant by stdin. Got it

**Comment by dylanhitt** [comment]
@SimonBaeumer, I think I would like to tackle this one for both stdin and url's. However I was think about doing #121 first. Are you trying to get this into the `v2.1.0` release? If so I can work on this first.

**Comment by SimonBaeumer** [comment]
Imho I would release `v2.1.0` like it is atm, upcoming features will just go straigt to `v2.2.0`.
But you can just start to work on your features, it does not matter for this in which version something is merged.
Versions in this project are just some points in times to download a specific feature set - and if we broke something we have the option to quickly jumping back to a version without the bugs :D

**Comment by SimonBaeumer** [comment]
@dylanhitt I think you can close it 👍
