### ISSUE TITLE
Moving commander to an orginisation

### ISSUE THREAD

**Issue by SimonBaeumer** [commander-cli/commander#134]
As the activity in this project grows I would like to suggest to move commander into its own organisation.

Benefits would be:

 - Code ownership is not mine alone
 - More people are encouraged to join the project
 - Hopefully better permission configurations for new contributors
 - Creating more packages together 

Downside:

 - Repo link would change (redirects are managed by github)

For me it is important that the project is fun to work with and helps us to learn new things - and as a side effect doing something useful for the community.

Is there interest in this step?

**Comment by dylanhitt** [comment]
I think this would be awesome.

Would you move [this repository](https://github.com/SimonBaeumer/cmd) into the org as well?

**Comment by SimonBaeumer** [comment]
> I think this would be awesome.
> 
> Would you move [this repository](https://github.com/SimonBaeumer/cmd) into the org as well?

Yes that makes sense!
I would just create an org `commander-cli`. If there are any other name suggestions I would love to hear them, otherwise I will try to migrate the repo next week.
