### ISSUE TITLE
user should be able to set the working dir with `--workdir`

### ISSUE THREAD

**Issue by dylanhitt** [commander-cli/commander#156]
### Description

A user should have the ability to override all empty tests `dir` with a command line argument such as `--workdir`.

This could require a major version bump. Currently in `config` section of a suite file workdir is known as `dir`. It would be nice if these matched.

We may want to  complete #131 as well before we do the version bump.

**Comment by SimonBaeumer** [comment]
> The --working-dir option looks like a good option, like make -C /dir.
Changing directory could be implemented with the syscall:
https://man7.org/linux/man-pages/man2/chdir.2.html
https://golang.org/src/os/file.go?s=8392:8420#L278
