### ISSUE TITLE
documented install command fails with go 1.16

### ISSUE THREAD

**Issue by rene00** [commander-cli/commander#166]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [ ] Did you perform a cursory search?

### Description

When attempting to install `commander` using `go get` *outside* of the `commander` project directory, it fails.
```bash
$ cd && go clean -cache -modcache && go get github.com/commander-cli/commander/cmd/commander
go get: github.com/commander-cli/commander@none updating to
        github.com/commander-cli/commander@v1.3.0: parsing go.mod:
        module declares its path as: github.com/SimonBaeumer/commander
                but was required as: github.com/commander-cli/commander
```
Running the `go get` command within the `commander` project directory completes successfully:
```bash
$ git clone https://github.com/commander-cli/commander && cd commander &&  go clean -cache -modcache && go get github.com/commander-cli/commander/cmd/commander
```

### Steps to Reproduce

1. Install `go` 1.16.
2. Attempt to install `commander` outside project directory:
```bash
cd && go clean -cache -modcache -i -r && go get github.com/commander-cli/commander/cmd/commander
```
**Expected behavior:**
A working `commander` binary installed in `GOBIN`.

**Actual behavior:**
`go get` fails.

### Specifications

 - Version: n/a but needs `go` `1.16` to reproduce.
 - Platform: tested on MacOS and Linux
 - Subsystem: 
 
You can get the version information from executing `commander --version`.

**Comment by rene00** [comment]
When setting `GO111MODULE=auto` or `GO111MODULE=off`, `go get` completes successfully:

```bash
$ cd && go clean -cache -modcache && GO111MODULE=auto go get github.com/commander-cli/commander/cmd/commander
```

**Comment by dylanhitt** [comment]
Hey @rene00 would you mind trying to recreate this again? I am unable to do so after #167

**Comment by dylanhitt** [comment]
Nevermind, I just reproduced it.

**Comment by rodrigoaguilera** [comment]
@dylanhitt Does this require a release to be really solved?
running 
```
go get github.com/commander-cli/commander/cmd/commander
```
on a fresh golang docker container I still get the error.

**Comment by dylanhitt** [comment]
@rodrigoaguilera that's more than likely the case. I think we also would need to change the docs to represent the v2 module. Like

```bash
go get github.com/commander-cli/commander/v2/cmd/commander
```

I can get a PR setup for a `v2.5.1` release.
