### ISSUE TITLE
Unable to run docker via kind cluster

### ISSUE THREAD

**Issue by d2iqpchavan** [commander-cli/commander#175]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you perform a cursory search?

### Description

I am trying to run commander to run custom tool test via docker and kind, its failing on docker path.  I tried searching on documentation but not able to resolve the test yet.  If I run same docker commands from CLI it does work and lists the clusters successfully 
docker ps -a --filter label=io.x-k8s.kind.cluster --format '{{.Label "io.x-k8s.kind.cluster"}}'"

Is there any method to add docker executable to test path?

### Steps to Reproduce
step 1: ./commander test --verbose
Fails with error:  

`Error:failed to list kind clusters when bootstrapping failed to list clusters: command "docker ps -a --filter label=io.x-k8s.kind.cluster --format '{{.Label "io.x-k8s.kind.cluster"}}'" failed with error: exec: "docker": executable file not found in $PATH`

**Expected behavior:** list the kind clusters

**Actual behavior:** Stderr throws the error above

### Specifications

 - Version: commander version 2.4.0
 - Platform: darwin arm64
 - Subsystem: 
 
You can get the version information from executing `commander --version`.

**Comment by dylanhitt** [comment]
Hey @d2iqpchavan,

Thank you for the issue. Just to be clear I'm understanding you, you're running command from a local shell. You're on operating in a container or anything right?

Also do you mind sharing a sample of you manifest if you can?

Thanks!

**Comment by d2iqpchavan** [comment]
Yes, I am running command from my local shell, (apple m1 darwin arm64 to be specific).
Sorry but I do not know what do you mean by manifest? Is this pre req to test via commander? Can you elaborate please?

**Comment by dylanhitt** [comment]
I apologize for not being clear.

What I meant to refer to is your test suite. Your `commander.yaml` file. I’d like to see your test job so I can replicate it. Your test suite should look something like.

```yaml
tests:
  it should print hello world:
    command: docker ps -a --filter label=io.x-k8s.kind.cluster --format '{{.Label "io.x-k8s.kind.cluster"}}'"
    stdout: hello world
    exit-code: 0
```

**Comment by d2iqpchavan** [comment]
the issue is the docker command is not independent, our internal tool command spins up docker as second step in the process

here is my test suite 

```
tests:
 konvoy create:
  command: ./konvoy create bootstrap --kind-cluster-image kindest/node:v1.21.2
  exit-code: 0
  stdout:
   contains:
    - Creating bootstrap
```

**Comment by dylanhitt** [comment]
I believe I understand now.

So ./konvoy is some type of internal tooling (binary, executable) that is making some form of exec() call to the system that has docker installed on it. I assume this where we are losing the context of the $PATH variable. 

I do not know enough about this executable to give a precise answer. I have hunch that could be related to how `docker` is being executed. [Something like this could help](https://stackoverflow.com/questions/44786643/exec-executable-file-not-found-in-path). 

I'll work up a quick test to confirm that `commander` operates as we expect based upon my current "hunch" and provide the results. Any additional context you could provide would be helpful.

**Comment by d2iqpchavan** [comment]
you are absolutely right. I tested docker and konvoy both on shell on the current path hence _I think_ your hunch is right. 
Let me try this meanwhile. THANK YOU!

**Comment by d2iqpchavan** [comment]
@dylanhitt do you want to brainstorm on this? or any suggestions on how do I proceed?

**Comment by dylanhitt** [comment]
@d2iqpchavan did you give what i described a shot? I won't get around to replicating what I believe is happening until next week.

**Comment by d2iqpchavan** [comment]
no worries - I am not familiar with source code of the konvoy project as much so so far I have not figured on updating the command there - I was trying to leverage this plugin on the top of konvoy.

**Comment by PossibleLlama** [comment]
I had a similar issue with a different executable, and getent not being found in the path when running via commander.

After some playing around with the application, it was a dependency of the executable that was using getent, and then causing the problem. The executable was fine when ran via bash or zsh (both of which found getent via `which getent`), but failing when ran via commander.

I fixed the issue by removing the dependency from the application.

**Comment by d2iqpchavan** [comment]
thanks for all your help. I am unblocked and the issue was with my local path and I added that as part of `env` in config

`config:
   env:
    PATH: ${PATH}`
