### ISSUE TITLE
Commands in Installation section try to download non-existing version

### ISSUE THREAD

**Issue by thetillhoff** [commander-cli/commander#189]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you perform a cursory search?

### Description

The [Installation section](https://github.com/commander-cli/commander#linux--osx) in the `README.md` tries to download v2.5.0 which doesn't seem to be released yet ;)

**Comment by dylanhitt** [comment]
Think this covers it https://github.com/commander-cli/commander/releases/tag/v2.5.0 😄
